Models/customer_info.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_TASK3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer_info
    {
       
        public int customer_id { get; set; }
        [Display(Name ="First Name")]
        [Required (ErrorMessage = "enter first name")]
        [StringLength(12, ErrorMessage = "max=12 char")]
        public string first_name { get; set; }
        [Display(Name = "Last Name")]
        [StringLength(12, ErrorMessage = "max=12 char")]
        [Required(ErrorMessage = "enter last_name")]

        public string last_name { get; set; }
        [Display(Name = "E_mail")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "enter email")]
        [RegularExpression(@"\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b")]
        public string email { get; set; }
        [Display(Name = "Number")]
        [Required(ErrorMessage = "enter your num")]
        [RegularExpression(@"^0(77|78|79)\d{7}$")]

        public string phone { get; set; }
        [Display(Name = "Age")]
        [Required(ErrorMessage = "enter your age")]
        [Range(18, 50,ErrorMessage ="out range")]
        public int age { get; set; }
        [Required ]
        [StringLength (10,ErrorMessage ="max=10 char")]
        [Display(Name = "JOB")]
        public string job_title { get; set; }
        [Required]
        [Display(Name = "Gender")]
        public bool gender { get; set; }
    }
}

Controllers/customer_infoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_TASK3.Models;

namespace MVC_TASK3.Controllers
{
    public class customer_infoController : Controller
    {
        private customersEntities db = new customersEntities();

        // GET: customer_info
        public ActionResult Index()
        {
            return View(db.customer_info.ToList());
        }

        // GET: customer_info/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer_info customer_info = db.customer_info.Find(id);
            if (customer_info == null)
            {
                return HttpNotFound();
            }
            return View(customer_info);
        }

        // GET: customer_info/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: customer_info/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "customer_id,first_name,last_name,email,phone,age,job_title,gender")] customer_info customer_info)
        {
            if (ModelState.IsValid)
            {
                db.customer_info.Add(customer_info);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer_info);
        }

        // GET: customer_info/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer_info customer_info = db.customer_info.Find(id);
            if (customer_info == null)
            {
                return HttpNotFound();
            }
            return View(customer_info);
        }

        // POST: customer_info/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "customer_id,first_name,last_name,email,phone,age,job_title,gender")] customer_info customer_info)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer_info).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer_info);
        }

        // GET: customer_info/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer_info customer_info = db.customer_info.Find(id);
            if (customer_info == null)
            {
                return HttpNotFound();
            }
            return View(customer_info);
        }

        // POST: customer_info/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            customer_info customer_info = db.customer_info.Find(id);
            db.customer_info.Remove(customer_info);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Controllers/serController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_TASK3.Models;

namespace MVC_TASK3.Controllers
{
    public class serController : Controller
    {
        private customersEntities db = new customersEntities();

        // GET: ser
        public ActionResult Index()
        {
            return View(db.customer_info.ToList());
        }

        // GET: ser/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer_info customer_info = db.customer_info.Find(id);
            if (customer_info == null)
            {
                return HttpNotFound();
            }
            return View(customer_info);
        }

        // GET: ser/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ser/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "customer_id,first_name,last_name,email,phone,age,job_title,gender")] customer_info customer_info)
        {
            if (ModelState.IsValid)
            {
                db.customer_info.Add(customer_info);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer_info);
        }

        // GET: ser/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer_info customer_info = db.customer_info.Find(id);
            if (customer_info == null)
            {
                return HttpNotFound();
            }
            return View(customer_info);
        }

        // POST: ser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "customer_id,first_name,last_name,email,phone,age,job_title,gender")] customer_info customer_info)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer_info).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer_info);
        }

        // GET: ser/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer_info customer_info = db.customer_info.Find(id);
            if (customer_info == null)
            {
                return HttpNotFound();
            }
            return View(customer_info);
        }

        // POST: ser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            customer_info customer_info = db.customer_info.Find(id);
            db.customer_info.Remove(customer_info);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        //public ActionResult ser1(string searching)
        //{
        //    var em = db.customer_info.Where(e => e.last_name.Contains(searching)).ToList();
        //    return View("Index", em);
        //}
        public ActionResult ser1(string searching,string ss)
        {
            if (searching == "fName")
            {
                var fname = db.customer_info.Where(s => s.first_name.Contains(ss) ).ToList();
                return View("Index", fname);
            }
            else if (searching == "lName")
            {
                var lname = db.customer_info.Where(s => s.last_name.Contains(ss)).ToList();
                return View("Index", lname);
            }
            else
            {
                var email = db.customer_info.Where(s => s.email.Contains(ss)).ToList();
                return View("Index", email);
            }
        }
    }
}

Views/customer_info/Create.cshtml
@model MVC_TASK3.Models.customer_info

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>customer_info</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.job_title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.job_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.job_title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.RadioButtonFor(Model => Model.gender, "femail")femail &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.RadioButtonFor(model => model.gender, "mail")mail 
                    @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/customer_info/Delete.cshtml
@model MVC_TASK3.Models.customer_info

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>customer_info</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.job_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.job_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/customer_info/Details.cshtml
@model MVC_TASK3.Models.customer_info

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>customer_info</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.job_title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.job_title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.customer_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/customer_info/Edit.cshtml
@model MVC_TASK3.Models.customer_info

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>customer_info</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.customer_id)

        <div class="form-group">
            @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.job_title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.job_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.job_title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.gender)
                    @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/customer_info/Index.cshtml
@model IEnumerable<MVC_TASK3.Models.customer_info>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("New Customer", "Create", null, new { @class = "btn btn-primary" })
</p>
@using (Html.BeginForm("ser1", "ser"))
{
    <p>
        <span>Search Options :</span>
        @Html.RadioButton("searching", "fName")<span>First Name</span>
        @Html.RadioButton("searching", "email")<span>Email</span>
        @Html.RadioButton("searching", "lName")<span>Last Name</span><br />

        @Html.TextBox("ss")
        <input type="submit" value="Search" class="btn btn-success" />
    </p>
   
    @*<p>

            @Html.TextBox("searching")
            <input type="submit" value="Search"/>
        </p>*@
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.first_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.last_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.job_title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gender)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.first_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.last_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.job_title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.customer_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.customer_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.customer_id })
            </td>
        </tr>
    }

</table>